# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Jan 24 15:48:10 2025
# ------------------------------------------------

package:
  name: conda-libmamba-solver
  version: 25.1.1
source:
  folder: src/
  sha256: 38d8b46d4890b8ebd948b4b2d9761f18d18d6fa4bef87f19bdad0a6f8e5371c8
  url: https://github.com/conda/conda-libmamba-solver/archive/refs/tags/25.1.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /croot/conda-libmamba-solver_1737733694612/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install src/ -vv --no-deps --no-build-isolation
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=25.1.1
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.12.31 h06a4308_0
    - expat 2.6.4 h6a678d5_0
    - hatch-vcs 0.3.0 py313h06a4308_1
    - hatchling 1.27.0 py313h06a4308_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - packaging 24.2 py313h06a4308_0
    - pathspec 0.10.3 py313h06a4308_0
    - pip 24.2 py313h06a4308_0
    - pluggy 1.5.0 py313h06a4308_0
    - python 3.13.1 hf623796_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h5eee18b_0
    - setuptools 75.1.0 py313h06a4308_0
    - setuptools-scm 8.1.0 py313h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - trove-classifiers 2024.10.14 py313h06a4308_0
    - tzdata 2025a h04d1e81_0
    - wheel 0.44.0 py313h06a4308_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - boltons >=23.0.0
    - conda >=23.7.3
    - libmambapy >=2
    - python >=3.9
test:
  commands:
    - CONDA_SOLVER=libmamba conda create -n test --dry-run scipy
    - conda create --solver libmamba -n test --dry-run scipy
  imports:
    - conda_libmamba_solver
about:
  description: 'The conda-libmamba-solver is a new solver for the conda package manager

    which uses the solver from the mamba project behind the scenes,

    while carefully implementing conda''s functionality and expected behaviors on
    top.

    The library used by mamba to do the heavy-lifting is called libsolv.

    '
  dev_url: https://github.com/conda/conda-libmamba-solver
  doc_url: https://conda.github.io/conda-libmamba-solver/
  home: https://github.com/conda/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: The fast mamba solver, now in conda!
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ac60cb4c-4d13-4d85-9dcd-ff84b484fe7c
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/conda-libmamba-solver-feedstock.git
  sha: 28054962163d57b078a7e1db1d59934641ed0f5a
  skip-lints:
    - missing_pip_check
